name: codekameleon
description: "Code Kameleon is your all-in-one coding companion. Learn popular languages like Java, Python, and JavaScript through engaging tutorials. Test your knowledge with quiz challenges, track your progress, and join a community of learners. Whether you're a beginner or looking to expand your skills, Code Kameleon has you covered."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.3+13

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_syntax_view: ^4.1.7
  google_fonts: ^6.2.1
  appinio_swiper: ^2.1.0
  flutter_markdown: ^0.7.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.1
  animations: ^2.0.11
  google_mobile_ads: ^5.3.1
  flutter_svg: ^2.0.17
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  provider: ^6.1.5
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  in_app_review: ^2.0.10
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/i18n/