name: codekameleon
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_syntax_view: ^4.1.4
  google_fonts: ^6.2.1
  provider: ^6.1.1
  appinio_swiper: ^2.1.0
  flutter_markdown: ^0.7.5
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
