name: codekameleon
description: "Code Kameleon is your all-in-one coding companion. Learn popular languages like Java, Python, and JavaScript through engaging tutorials. Test your knowledge with quiz challenges, track your progress, and join a community of learners. Whether you're a beginner or looking to expand your skills, Code Kameleon has you covered."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.7+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_syntax_view: ^4.1.7
  google_fonts: ^6.2.1
  appinio_swiper: ^2.1.0
  flutter_markdown: ^0.7.5
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.1
  animations: ^2.0.11
  #flutter_card_swiper: ^7.0.2
  google_mobile_ads: ^5.3.1
  flutter_svg: ^2.0.17
#  firebase_auth: ^5.5.1
#  flutter_bloc: ^9.1.0
#  firebase_core: ^3.12.1
#  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
