// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjUqcKaj8JMsca577PDTsiP1yAJp_WkY',
    appId: '1:481621239614:android:4c515d0b751114f1912e6f',
    messagingSenderId: '481621239614',
    projectId: 'codekameleon',
    storageBucket: 'codekameleon.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1NYR90zE1rbOSfFyt20auXS_CKtnh50',
    appId: '1:481621239614:web:4d136510a9f1bca0912e6f',
    messagingSenderId: '481621239614',
    projectId: 'codekameleon',
    authDomain: 'codekameleon.firebaseapp.com',
    storageBucket: 'codekameleon.firebasestorage.app',
    measurementId: 'G-0RFJLGJWG7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAir-Ztha5l1otGtFH9aDWlJudEsO6bn1w',
    appId: '1:481621239614:ios:cf367ebf0631b17e912e6f',
    messagingSenderId: '481621239614',
    projectId: 'codekameleon',
    storageBucket: 'codekameleon.firebasestorage.app',
    androidClientId: '481621239614-7v709hcfdsj9vt3bpj1luuanmgtdlv5k.apps.googleusercontent.com',
    iosClientId: '481621239614-sjm7m17k76l9prtke3l7gavghteudbjv.apps.googleusercontent.com',
    iosBundleId: 'com.techlyverse.codekameleon',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir-Ztha5l1otGtFH9aDWlJudEsO6bn1w',
    appId: '1:481621239614:ios:cf367ebf0631b17e912e6f',
    messagingSenderId: '481621239614',
    projectId: 'codekameleon',
    storageBucket: 'codekameleon.firebasestorage.app',
    androidClientId: '481621239614-7v709hcfdsj9vt3bpj1luuanmgtdlv5k.apps.googleusercontent.com',
    iosClientId: '481621239614-sjm7m17k76l9prtke3l7gavghteudbjv.apps.googleusercontent.com',
    iosBundleId: 'com.techlyverse.codekameleon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1NYR90zE1rbOSfFyt20auXS_CKtnh50',
    appId: '1:481621239614:web:2739a2ccdcac3309912e6f',
    messagingSenderId: '481621239614',
    projectId: 'codekameleon',
    authDomain: 'codekameleon.firebaseapp.com',
    storageBucket: 'codekameleon.firebasestorage.app',
    measurementId: 'G-YNX0RQVKCR',
  );

}